export const EXPERIENCE = [
  {
    role: "Software Engineering Intern",
    company: "Creative Software",
    period: "2026 – Present",
    initials: "CS",
    description:
      "Full-stack software engineering intern contributing to real client and internal projects. I build and ship production-ready features across the stack, working closely with senior developers.",
    responsibilities: [
      "Developing full-stack web applications",
      "Building responsive frontend interfaces with React, Next.js, and Tailwind CSS",
      "Implementing backend functionality and REST API integration",
      "Handling authentication, authorization, and database operations",
      "Debugging and fixing production issues",
      "Collaborating with senior developers using Git and code review workflows",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "MySQL",
      "Tailwind CSS",
      "REST APIs",
      "Git",
      "GitHub",
      "Postman",
    ],
    achievements: [
      "Contributing to production software used by real clients",
      "Collaborating with senior engineers through code review and delivery",
      "Fixing production bugs and improving application reliability",
    ],
  },
  {
    role: "Independent Full-Stack Developer",
    company: "Independent",
    period: "2024 – Present",
    initials: "FS",
    description:
      "Building and shipping my own full-stack applications — e-commerce platforms, a hotel booking system, and REST APIs — to deepen my skills across the entire stack and deliver production-ready software.",
    responsibilities: [
      "Designing and building full-stack applications from scratch",
      "Implementing REST APIs with authentication and role-based access control",
      "Integrating MongoDB and MySQL databases",
      "Deploying and maintaining live applications on Vercel and Render",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "MySQL",
      "Tailwind CSS",
      "Git",
      "Vercel",
      "Render",
    ],
    achievements: [
      "Shipped 10+ projects, including several full-stack applications",
      "Maintained live deployments and iterated based on real usage",
      "Continuously learning modern patterns like TypeScript and testing",
    ],
  },
];
